### ISSUE TITLE
Running into error for withSkinSegmentation

### ISSUE THREAD

**Issue by rajpratim** [Bishalsarang/The-Sign-Language-Platform#3]
Hi Bishal, 

I am running into the below error while running translator.py with parameter 'y'

>>translator.py -m y

Error:
(tensorflow_env) C:\Users\xxxx>python P:\Battleground\IdeaHack\ASL\translator.py -m y
Using TensorFlow backend.
2020-03-11 13:00:25.214843: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "P:\Battleground\IdeaHack\ASL\translator.py", line 248, in <module>
    withSkinSegment()
  File "P:\Battleground\IdeaHack\ASL\translator.py", line 105, in withSkinSegment
    contours, _ = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL, 2)
ValueError: too many values to unpack (expected 2)

**Comment by Bishalsarang** [comment]
Try commenting out line 105 and uncomment line 106.
Seems like you are running different open cv version. 
See if that works.

**Comment by rajpratim** [comment]
Yeah got it..Closing the issue
